# Generated by Django 4.0 on 2022-01-03 14:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
        ('blog_app', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('82cb6db4-e0d5-4bc5-8307-ab79df0bf351'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('commenter', 'post')},
        ),
    ]
