# Generated by Django 4.0 on 2022-01-03 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_alter_comment_id_alter_comment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4d025a6c-a479-40b9-9764-fd3de4a9ce24'), editable=False, primary_key=True, serialize=False),
        ),
    ]
