# Generated by Django 4.0 on 2022-01-03 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_alter_comment_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9a9c950a-5e34-436e-aab9-27112a0645e3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
