# Generated by Django 4.0 on 2022-01-04 15:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
        ('blog_app', '0008_alter_comment_unique_together_alter_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('46055e2e-4dc4-4073-8d65-75216147e4a9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('commenter', 'post')},
        ),
    ]
